### ISSUE TITLE
Get wallet / asset information

### ISSUE THREAD

**Issue by BerinikeTech** [amosproj/amos2021ws07-nft-development#34]
## User story
1. As a user
2. I want to see my purchased currencies and my public address
3. So that I have an overview of my assets

## Acceptance criteria
* As soon as the frontend triggers the wallet adding, the backend fetches the correct information and sends it back to the frontend

**Comment by steinkohl** [comment]
A brief critical review:

After a wallet is added to the account, this address is stored in the Wallet Collection. The frontend always has access to the address as long as the session is active.

This means that the query for the stored NFTs and other blockchain information can also be retrieved from the frontend at any time, since no further information is required for this.

This raises the question for me whether the functionality should really be integrated into the backend, as it creates potential for misuse or at least for problems. The query is relatively complex and could significantly affect the load on the server as soon as all users continuously update their page, which is likely to be the case with a drop.

**Comment by tuilagio** [comment]
I think fetching Wallet/assets information can be done in frontend totally, without involving BE at all?

**Comment by krisutofu** [comment]
Or do you mean, there should be a security check when requests are sent to the backend?

**Comment by steinkohl** [comment]
No everything can be done in the frontend, on the CPU of the users. If we put the function in the backend, we have to ensure CPU headroom on the server. In other words higher cost with no significant added value. Moreover, it could also carry security problems...

**Comment by krisutofu** [comment]
This is fine as long as security does not only depend on the client side (which cannot be trusted).

**Comment by steinkohl** [comment]
@krisutofu 
There also is no private information exchanged / transferred, this backend function would only aggregate information which is public accessible on the blockchain. 
But if it would be sensitive data, i would disagree with you. It's always safer for the user, if the processing of the data can be handled at local cpu -> at the code in the frontend
